### ISSUE TITLE
New Algo Addition 

### ISSUE THREAD

**Issue by VesperAkshay** [VesperAkshay/File_Compression#1]
**Summary:**  
We propose the addition of a new algorithm to enhance the functionality of our project. This algorithm aims to improve performance and efficiency.

**Comment by memyselfandglitch** [comment]
Could I work on this issue? Since the algorithms used are lossless I could add a lossy one, maybe one related to image compression or would text compression itself be better? Arithmetic coding has better compression ratio than Huffman I could add that.

**Comment by Sohammhatre10** [comment]
@memyselfandglitch lossy alogs for text compression aren't ideal as it may cause hallucinations for text-coded data like passwords and sensitive stuff while decoding, while for image compression JPEG using DCT works Ig. 
So @VesperAkshay should I work on JPEG DCT for image compression, regarding the same issue?

**Comment by VesperAkshay** [comment]
Yes you can work on adding the image compression in the project 
But a separate option for image compression

**Comment by VesperAkshay** [comment]
> Could I work on this issue? Since the algorithms used are lossless I could add a lossy one, maybe one related to image compression or would text compression itself be better? Arithmetic coding has better compression ratio than Huffman I could add that.

Adding a lossy compression is not feasible for txt compression 
If you want to add some new algo for text compression you can go for some lossless compression like Brotil or PPM
